LinkedList:
	gcc -Wall -w -Wextra -c LinkedList.c -o LinkedList.o
	gcc -Wall -w -Wextra -c LinkedList_test.c -o LinkedList_test.o
	gcc LinkedList.o LinkedList_test.o -o LinkedList

clean:
	rm -f *.o
	rm -f LinkedList
